# Run the containers: `docker-compose up --build -d`
# Stop them: `docker-compose up --build -d`
# Visit the site: Put `localhost` into the browser.

version: '3.8'
services:
  tekku_php_apache:
    container_name: tekku_php_apache
    build: 
      context: .
      dockerfile: Dockerfile.php-apache
    ports:
    - 80:80
    volumes:
    - .:/var/www/html/
    - ./.env:/var/www/html/../.env
    - ./php.ini:/usr/local/etc/php/php.ini
    environment:
    - DOCUMENT_ROOT=/var/www/html/
    env_file:
    - .env

  tekku_maria_db:
    hostname: ${DB_HOST}
    build:
      context: .
      dockerfile: Dockerfile.mysql
    restart: 'always'
    volumes: 
      - "/var/lib/mysql/data:/data"
      - "/var/lib/mysql/logs:/logs"
      - /var/docker/mariadb/conf:/etc/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "123"
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
